### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by skeddles** [rez0n/docker-nodebb#217]
hate to be that guy, but would love a 1.17.1 version. tried to upgrade it myself but really have no idea how docker packages work (or docker really...). Right now I get two different errors on 1.16.2 and 1.17.0 due to plugin versions, but 1.17.1 will fix it

**Comment by rez0n** [comment]
Hi @skeddles, usually it built automatically, but for some reason, auto-build was broken and I have no time to investigate it.
1.17.1 ready - https://github.com/users/rez0n/packages/container/package/nodebb
